# Generated by Django 4.2.11 on 2026-05-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradora',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='areasolicitante',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipoidentificacion',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipoplanilla',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tiporegional',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tiposolicitud',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='administradora',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('codigo',), name='unique_administradora_codigo_active'),
        ),
        migrations.AddConstraint(
            model_name='areasolicitante',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('codigo',), name='unique_areasolicitante_codigo_active'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('codigo',), name='unique_documento_codigo_active'),
        ),
        migrations.AddConstraint(
            model_name='tipoidentificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('codigo',), name='unique_tipoidentificacion_codigo_active'),
        ),
        migrations.AddConstraint(
            model_name='tipoplanilla',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('codigo',), name='unique_tipoplanilla_codigo_active'),
        ),
        migrations.AddConstraint(
            model_name='tiporegional',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('nombre',), name='unique_tiporegional_nombre_active'),
        ),
        migrations.AddConstraint(
            model_name='tiposolicitud',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('codigo',), name='unique_tiposolicitud_codigo_active'),
        ),
    ]
