# Generated by Django 4.2.11 on 2026-05-22 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


TIPO_MAP = {
    'CONTRIBUCION':    'Contribución',
    'PRESTACION':      'Prestación',
    'ADMINISTRATIVO':  'Administrativo',
    'OTRO':            'Otro',
}


def seed_categorias(apps, schema_editor):
    CategoriaCausal = apps.get_model('catalogos', 'CategoriaCausal')
    for nombre in TIPO_MAP.values():
        CategoriaCausal.objects.get_or_create(nombre=nombre)


def map_tipo_to_fk(apps, schema_editor):
    TipoCausal = apps.get_model('catalogos', 'TipoCausal')
    CategoriaCausal = apps.get_model('catalogos', 'CategoriaCausal')
    for causal in TipoCausal.objects.all():
        nombre = TIPO_MAP.get(causal.tipo)
        if nombre:
            try:
                causal.tipo_fk = CategoriaCausal.objects.get(nombre=nombre)
                causal.save(update_fields=['tipo_fk'])
            except CategoriaCausal.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0002_partial_unique_constraints_soft_delete'),
    ]

    operations = [
        # 1. Crear tabla CategoriaCausal
        migrations.CreateModel(
            name='CategoriaCausal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de Causal',
                'verbose_name_plural': 'Categorías de Causal',
                'ordering': ['nombre'],
            },
        ),
        # 2. Poblar categorías iniciales
        migrations.RunPython(seed_categorias, migrations.RunPython.noop),
        # 3. Agregar columna FK temporal
        migrations.AddField(
            model_name='tipocausal',
            name='tipo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.categoriacausal'),
        ),
        # 4. Migrar datos: string → FK
        migrations.RunPython(map_tipo_to_fk, migrations.RunPython.noop),
        # 5. Eliminar columna vieja
        migrations.RemoveField(model_name='tipocausal', name='tipo'),
        # 6. Renombrar tipo_fk → tipo
        migrations.RenameField(model_name='tipocausal', old_name='tipo_fk', new_name='tipo'),
    ]
