# Generated by Django 4.2.11 on 2026-05-30 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_remove_formulario_contribucion'),
        ('catalogos', '0003_categoria_causal_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocausal',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='causales', to='catalogos.categoriacausal'),
        ),
        migrations.DeleteModel(
            name='FormularioContribucion',
        ),
    ]
