# Generated by Django 4.2.11 on 2026-05-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_remove_formulario_contribucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocausal',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='causales', to='catalogos.documento', verbose_name='Documentos requeridos'),
        ),
    ]
