# Generated by Django 4.2.11 on 2026-05-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='total_ganado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
