# Generated by Django 4.2.11 on 2026-05-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('solicitudes', '0002_add_total_ganado_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='area_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_unidad', to='catalogos.unidad'),
        ),
    ]
