# Generated by Django 4.2.11 on 2026-05-18 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0003_area_solicitante_to_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
