# Generated by Django 4.2.11 on 2026-05-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_rename_apro_to_rect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='formulario_contribucion',
        ),
    ]
