# Generated by Django 4.2.11 on 2026-05-31 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_add_notif_estado_plantilla_to_solicitud'),
        ('solicitudes', '0007_remove_formulario_contribucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='notif_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_notif', to='catalogos.estadonotificacion'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='notif_plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_notif', to='catalogos.plantillaobservacion'),
        ),
    ]
