# Generated by Django 4.2.11 on 2026-05-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_add_notif_estado_plantilla_to_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacorasolicitud',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('BOR', 'Borrador'), ('PEND', 'Pendiente'), ('ASIG', 'Asignado'), ('REV', 'En Revisión'), ('RECT', 'Rectificado'), ('RECH', 'Rechazado'), ('DEV', 'Devuelto'), ('FIN', 'Finalizado')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bitacorasolicitud',
            name='estado_nuevo',
            field=models.CharField(blank=True, choices=[('BOR', 'Borrador'), ('PEND', 'Pendiente'), ('ASIG', 'Asignado'), ('REV', 'En Revisión'), ('RECT', 'Rectificado'), ('RECH', 'Rechazado'), ('DEV', 'Devuelto'), ('FIN', 'Finalizado')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('BOR', 'Borrador'), ('PEND', 'Pendiente'), ('ASIG', 'Asignado'), ('REV', 'En Revisión'), ('RECT', 'Rectificado'), ('RECH', 'Rechazado'), ('DEV', 'Devuelto'), ('FIN', 'Finalizado')], default='BOR', max_length=10),
        ),
    ]
