# Generated by Django 4.2.11 on 2026-05-17 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('accounts', '0003_add_agencia_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='catalogos.tiporegional'),
        ),
    ]
